# serverless.yml

service: greenGear

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  createUser:
    handler: index.handler
    events:
      - http: 'POST /user/new'